from __future__ import annotations

DEFAULT_WORKSPACE_NAME = "Dashboard"
DEFAULT_COMPANY_NAME = "Independent Contractor"
DEFAULT_MONTHLY_CAPACITY_HOURS = 140

MAX_PROJECT_BUDGET_CENTS = 100_000_000
MAX_TASK_ESTIMATE_MINUTES = 60 * 24 * 30
